include styles/

./: styles/

# The list of pairs that specify the plugins loaded by libs{Qt6Widgets} and
# whether they are included for the target platform.
#
widgets_plugins = \
  styles/libs{qmacstyle}@$macos \
  styles/libs{qmodernwindowsstyle}@$windows
