include styles/

./: styles/

# This alias presents a single target that depends on all of the plugins
# loaded by libs{Qt6Widgets} for a specific platform.
#
alias{Qt6WidgetsPlugins}: styles/libs{qmacstyle}: include = $macos
alias{Qt6WidgetsPlugins}: styles/libs{qwindowsvistastyle}: include = $windows
