import libs  = libpcre2%lib{pcre2-16}
import libs += libtinycbor%lib{tinycbor}
import libs += libz%lib{z}

# Target metadata, see also --build2-metadata in main.cpp.
#
# Note that qt6rcc does not query any environment variables that can affect
# its output.
#
exe{qt6rcc}:
{
  export.metadata = 1 qt6rcc
  qt6rcc.name = [string] rcc
  qt6rcc.version  = [string] $version
  qt6rcc.checksum = [string] $version
}

windows = ($cxx.target.class == 'windows')
unix    = ($cxx.target.class != 'windows')
macos   = ($cxx.target.class == 'macos')

# The upstream build creates a static bootstrap library consisting of a
# selection of the QtCore sources which is then used to build moc, rcc, and
# tracegen.
#

# The rcc executable source files.
#
rcc_src = rcc main

# The QtCore source files required to build the rcc executable.
#
# Note that the upstream RCC is linked against the QtCore library proper but
# we cannot do that because that library is/should not be in the host
# configuration.
#
# The following set of sources is mostly based on the sources in the bootstrap
# library's CMakeLists.txt (upstream/qtbase/src/tools/bootstrap/). The
# following sources are required in addition:
#
# - The XML stream sources (see
#   QtCore/private/QtCore/private/qconfig-bootstrapped.h).
#
# - qbuffer (used by QXmlStreamWriter) and qendian (used by the UTF-16 and
#   UTF-32 codecs which QXmlStreamReader requires).
#
# - qdirlisting (used to add directories to resource collections).
#
core_src = QtCore/global/qalloc                         \
           QtCore/global/qassert                        \
           QtCore/global/qendian                        \
           QtCore/global/qtenvironmentvariables         \
           QtCore/io/qabstractfileengine                \
           QtCore/io/qbuffer                            \
           QtCore/io/qdir                               \
           QtCore/io/qdirlisting                        \
           QtCore/io/qfile                              \
           QtCore/io/qfiledevice                        \
           QtCore/io/qfileinfo                          \
           QtCore/io/qfilesystemengine                  \
           QtCore/io/qfilesystementry                   \
           QtCore/io/qfsfileengine                      \
           QtCore/io/qfsfileengine_iterator             \
           QtCore/io/qiodevice                          \
           QtCore/kernel/qcoreapplication               \
           QtCore/kernel/qmetatype                      \
           QtCore/kernel/qsystemerror                   \
           QtCore/serialization/qcborcommon             \
           QtCore/serialization/qcborstreamwriter       \
           QtCore/serialization/qcborvalue              \
           QtCore/serialization/qjsonarray              \
           QtCore/serialization/qjsoncbor               \
           QtCore/serialization/qjsondocument           \
           QtCore/serialization/qjsonobject             \
           QtCore/serialization/qjsonparser             \
           QtCore/serialization/qjsonvalue              \
           QtCore/serialization/qjsonwriter             \
           QtCore/serialization/qtextstream             \
           QtCore/serialization/qxmlstream              \
           QtCore/serialization/qxmlstreamgrammar       \
           QtCore/serialization/qxmlutils               \
           QtCore/text/qbytearray                       \
           QtCore/text/qbytearraylist                   \
           QtCore/text/qbytearraymatcher                \
           QtCore/text/qlatin1stringmatcher             \
           QtCore/text/qlocale                          \
           QtCore/text/qlocale_tools                    \
           QtCore/text/qregularexpression               \
           QtCore/text/qstring                          \
           QtCore/text/qstringbuilder                   \
           QtCore/text/qstringconverter                 \
           QtCore/text/qstringlist                      \
           QtCore/time/qcalendar                        \
           QtCore/time/qdatetime                        \
           QtCore/time/qgregoriancalendar               \
           QtCore/time/qlocaltime                       \
           QtCore/time/qromancalendar                   \
           QtCore/time/qtimezone                        \
           QtCore/tools/qarraydata                      \
           QtCore/tools/qcommandlineoption              \
           QtCore/tools/qcommandlineparser              \
           QtCore/tools/qhash                           \
           QtCore/tools/qringbuffer

# The UNIX-specific QtCore source files required to build rcc. Note that
# this includes Mac OS.
#
# Note that qfilesystemengine_unix is handled separately (see below).
#
unix_core_src = QtCore/io/qfilesystemiterator_unix      \
                QtCore/io/qfsfileengine_unix            \
                QtCore/kernel/qcore_unix

# The Windows-specific QtCore source files required to build rcc.
#
win_core_src = QtCore/io/qfilesystemengine_win          \
               QtCore/io/qfilesystemiterator_win        \
               QtCore/io/qfsfileengine_win              \
               QtCore/kernel/qfunctions_win

# The Mac OS-specific Objective-C++ QtCore source files required to build
# rcc.
#
macos_core_src_mm = QtCore/kernel/qcore_foundation \
                    QtCore/kernel/qcore_mac

all_core_src = $core_src $unix_core_src QtCore/io/qfilesystemengine_unix \
               $win_core_src $macos_core_src_mm

gen_hdr = QtCore/qtcoreexports QtCore/qconfig QtCore/qtdeprecationdefinitions

exe{qt6rcc}: hxx{** -{$gen_hdr} +QtCore/Q*.} h{$gen_hdr}        \
             cxx{$core_src $rcc_src}                            \
             testscript

exe{qt6rcc}: cxx{$unix_core_src}:    include = $unix
exe{qt6rcc}: mm{$macos_core_src_mm}: include = $macos
exe{qt6rcc}: cxx{$win_core_src}:     include = $windows

# On Apple platforms qfilesystemengine_unix.cpp is compiled as Objective-C++
# (see upstream/qtbase/src/tools/bootstrap/CMakeLists.txt).
#
if $macos
  exe{qt6rcc}: mm{QtCore/io/qfilesystemengine_unix.cpp}
else
  exe{qt6rcc}: cxx{QtCore/io/qfilesystemengine_unix}: include = $unix

# Ensure included C and C++ source files and other files are included in the
# distribution.
#
exe{qt6rcc}: cxx{3rdparty/siphash/siphash}              \
             cxx{** -{$rcc_src                          \
                      $core_src                         \
                      $unix_core_src                    \
                      QtCore/io/qfilesystemengine_unix  \
                      $win_core_src}}                   \
             file{cmake.conf}: include = adhoc

# Generated headers and source files.
#
using autoconf

QtCore/h{qconfig}: in.symbol = '$'

# Extract the copyright string from upstream/qtbase/.cmake.conf.
#
qt_copyright = $process.run_regex(cat $src_base/cmake.conf,             \
                                  '^\s*set\(QT_COPYRIGHT\s+"(.+)"\)',   \
                                  '\1')

# All-Qt public configuration header. Included by other Qt libraries via
# QtCore/qtconfiginclude.h.
#
# See the .in file for more information.
#
QtCore/h{qconfig}: QtCore/in{qconfig}
{
  autoconf.prefix = qconfig_

  QT_VERSION_STR="$version.major.$version.minor.$version.patch"
  QT_VERSION_MAJOR="$version.major"
  QT_VERSION_MINOR="$version.minor"
  QT_VERSION_PATCH="$version.patch"

  QT_COPYRIGHT="$qt_copyright"
}

QtCore/h{qtcoreexports}: QtCore/in{qtcoreexports}
{
  in.symbol = '@'
  header_base_name_upper = QTCOREEXPORTS
  module_define_infix    = CORE
}

# Deprecation cut-off macros. See libQt6Core/QtCore/buildfile for details.
#
QtCore/h{qtdeprecationdefinitions}: QtCore/in{qtdeprecationdefinitions}
{
  in.symbol = '@'
  QT_DISABLE_DEPRECATED_UP_TO = ($windows ? 0x040800 : 0x050000)
  QT_WARN_DEPRECATED_UP_TO    = 0x070000
}

exe{qt6rcc}: $libs

cxx.poptions =+                                                                 \
  "-I$out_root/rcc"        "-I$src_root/rcc"                                    \
  "-I$out_root/rcc/QtCore" "-I$src_root/rcc/QtCore"                             \
                           "-I$src_root/rcc/QtCore/private"                     \
                           "-I$src_root/rcc/QtCore/private/QtCore"              \
                           "-I$src_root/rcc/QtCore/private/QtCore/private"

# Add platform-specific header directories, libraries, compilation options,
# and macro definitions.
#
# Every directory under mkspecs/ contains a unique `qplatformdefs.h`.
#
# Note that Mac OS with GCC is not supported by upstream (see README-DEV for
# details).
#
switch $cxx.target.class, $cxx.id, $cxx.target.system
{
  case 'linux', 'gcc'
    cxx.poptions += "-I$src_root/rcc/mkspecs/linux-g++"
  case 'linux', 'clang'
    cxx.poptions += "-I$src_root/rcc/mkspecs/linux-clang"
  case 'macos', 'clang-apple'
  {
    cxx.poptions += "-I$src_root/rcc/mkspecs/macx-clang"
    cxx.libs     += -framework AppKit                   \
                    -framework CoreServices             \
                    -framework Foundation               \
                    -framework IOKit                    \
                    -framework Security                 \
                    -framework UniformTypeIdentifiers
  }
  case 'bsd', 'clang', 'freebsd'
    cxx.poptions += "-I$src_root/rcc/mkspecs/freebsd-clang"
  case 'bsd', 'gcc', 'openbsd'
    cxx.poptions += "-I$src_root/rcc/mkspecs/openbsd-g++"
  case 'bsd', 'gcc', 'netbsd'
    cxx.poptions += "-I$src_root/rcc/mkspecs/netbsd-g++"
  case 'windows', 'msvc'
  {
    cxx.poptions += "-I$src_root/rcc/mkspecs/win32-msvc"
    cxx.libs += ole32.lib advapi32.lib netapi32.lib shell32.lib user32.lib
  }
  case 'windows', 'msvc-clang' | 'clang'
  {
    cxx.poptions += "-I$src_root/rcc/mkspecs/win32-clang-msvc"
    cxx.libs += ole32.lib advapi32.lib netapi32.lib shell32.lib user32.lib
  }
  case 'windows', 'gcc', 'mingw32'
  {
    cxx.poptions += "-I$src_root/rcc/mkspecs/win32-g++"
    cxx.coptions += -fno-keep-inline-dllexport
    cxx.libs     += -lole32 -ladvapi32 -lnetapi32 -lshell32 -luser32 -luuid
  }
}

# Required by QObjCWeakPointer (see
# upstream/qtbase/src/tools/bootstrap/CMakeLists.txt).
#
if $macos
  obj{QtCore/kernel/qcore_mac}: cxx.coptions += -fobjc-weak

cxx.poptions += -DQT_NO_CAST_FROM_ASCII

# Make QDir's directory entry listing available (used by the --project option)
# given that we compile QDirListing (see
# downstream/qtbase/src/corelib/io/qdir.cpp).
#
cxx.poptions += -DBUILD2_QT_BOOTSTRAP_DIRLISTING

obj{$all_core_src}: cxx.poptions += $bootstrap_macros
obj{$rcc_src}:      cxx.poptions += $compiler_macros                 \
                                    -DQT_RCC                         \
                                    -DQT_NO_URL_CAST_FROM_STRING     \
                                    -DQT_USE_NODISCARD_FILE_OPEN

# Disable exceptions on the rcc objects.
#
switch $cxx.class
{
  case 'gcc'
  {
    obj{$rcc_src}:
    {
      cxx.poptions += -DQT_NO_EXCEPTIONS
      cxx.coptions += -fno-exceptions
    }
  }
  case 'msvc'
  {
    obj{$rcc_src}:
    {
      cxx.poptions += -DQT_NO_EXCEPTIONS
      cxx.coptions += /EHs- /EHc-
    }
  }
}
