include imageformats/
include platforminputcontexts/
include platforms/

./: platforms/ platforminputcontexts/ imageformats/

# This alias presents a single target that depends on all of the plugins
# loaded by libs{Qt6Gui} for a specific platform.
#
alias{Qt6GuiPlugins}: imageformats/libs{qgif qico qjpeg}

alias{Qt6GuiPlugins}:                                                   \
  platforms/libs{qxcb}                                                  \
  platforminputcontexts/libs{composeplatforminputcontextplugin}:        \
    include = ($linux || $bsd)

alias{Qt6GuiPlugins}: platforms/libs{qcocoa}:   include = $macos
alias{Qt6GuiPlugins}: platforms/libs{qwindows}: include = $windows
