include imageformats/
include platforminputcontexts/
include platforms/

./: platforms/ platforminputcontexts/ imageformats/

# The list of pairs that specify the plugins loaded by libs{Qt6Gui} and
# whether they are included for the target platform.
#
gui_plugins = \
  imageformats/libs{qgif}@true \
  imageformats/libs{qico}@true \
  imageformats/libs{qjpeg}@true \
  platforms/libs{qxcb}@($linux || $bsd) \
  platforminputcontexts/libs{composeplatforminputcontextplugin}@($linux || $bsd) \
  platforms/libs{qcocoa}@$macos \
  platforms/libs{qwindows}@$windows
