import libs  = libpcre2%lib{pcre2-16}
import libs += libtinycbor%lib{tinycbor}

# Target metadata, see also --build2-metadata in main.cpp.
#
exe{qt6moc}:
{
  export.metadata = 1 qt6moc
  qt6moc.name = [string] moc
  qt6moc.version  = [string] $version
  qt6moc.checksum = [string] $version
  qt6moc.environment = [strings] CPATH CPLUS_INCLUDE_PATH INCLUDE
}

windows = ($cxx.target.class == 'windows')
unix    = ($cxx.target.class != 'windows')
macos   = ($cxx.target.class == 'macos')

# The upstream build creates a static bootstrap library consisting of a
# selection of the QtCore sources which is then used to build moc, rcc, and
# tracegen.
#

# The moc executable source files.
#
# Note that we don't use wildcards (here and for core_src below) because it's
# a subset of sources and it's easier to just take the list from upstream than
# to keep track of exclusions.
#
moc_src = collectjson  \
          generator    \
          main         \
          moc          \
          parser       \
          preprocessor \
          token

# The QtCore source files required to build the moc executable. (These all go
# into the bootstrap library in the upstream build; see
# upstream/qtbase/src/tools/bootstrap/CMakeLists.txt.)
#
# Note that qendian is required in addition because the UTF-16 and UTF-32
# codecs are enabled for all the Qt compilers (see
# downstream/qtbase/src/corelib/text/qstringconverter.cpp).
#
core_src = QtCore/global/qalloc                         \
           QtCore/global/qassert                        \
           QtCore/global/qendian                        \
           QtCore/global/qtenvironmentvariables         \
           QtCore/io/qabstractfileengine                \
           QtCore/io/qdir                               \
           QtCore/io/qfile                              \
           QtCore/io/qfiledevice                        \
           QtCore/io/qfileinfo                          \
           QtCore/io/qfilesystemengine                  \
           QtCore/io/qfilesystementry                   \
           QtCore/io/qfsfileengine                      \
           QtCore/io/qfsfileengine_iterator             \
           QtCore/io/qiodevice                          \
           QtCore/kernel/qcoreapplication               \
           QtCore/kernel/qmetatype                      \
           QtCore/kernel/qsystemerror                   \
           QtCore/serialization/qcborcommon             \
           QtCore/serialization/qcborstreamwriter       \
           QtCore/serialization/qcborvalue              \
           QtCore/serialization/qjsonarray              \
           QtCore/serialization/qjsoncbor               \
           QtCore/serialization/qjsondocument           \
           QtCore/serialization/qjsonobject             \
           QtCore/serialization/qjsonparser             \
           QtCore/serialization/qjsonvalue              \
           QtCore/serialization/qjsonwriter             \
           QtCore/serialization/qtextstream             \
           QtCore/text/qbytearray                       \
           QtCore/text/qbytearraylist                   \
           QtCore/text/qbytearraymatcher                \
           QtCore/text/qlatin1stringmatcher             \
           QtCore/text/qlocale                          \
           QtCore/text/qlocale_tools                    \
           QtCore/text/qregularexpression               \
           QtCore/text/qstring                          \
           QtCore/text/qstringbuilder                   \
           QtCore/text/qstringconverter                 \
           QtCore/text/qstringlist                      \
           QtCore/time/qcalendar                        \
           QtCore/time/qdatetime                        \
           QtCore/time/qgregoriancalendar               \
           QtCore/time/qlocaltime                       \
           QtCore/time/qromancalendar                   \
           QtCore/time/qtimezone                        \
           QtCore/tools/qarraydata                      \
           QtCore/tools/qcommandlineoption              \
           QtCore/tools/qcommandlineparser              \
           QtCore/tools/qhash                           \
           QtCore/tools/qringbuffer

# The UNIX-specific QtCore source files required to build moc. Note that
# this includes Mac OS.
#
# Note that qfilesystemengine_unix is handled separately (see below).
#
unix_core_src = QtCore/io/qfilesystemiterator_unix \
                QtCore/io/qfsfileengine_unix       \
                QtCore/kernel/qcore_unix

# The Windows-specific QtCore source files required to build moc.
#
win_core_src = QtCore/io/qfilesystemengine_win          \
               QtCore/io/qfilesystemiterator_win        \
               QtCore/io/qfsfileengine_win              \
               QtCore/kernel/qfunctions_win

# The Mac OS-specific Objective-C++ QtCore source files required to build
# moc.
#
macos_core_src_mm = QtCore/kernel/qcore_foundation \
                    QtCore/kernel/qcore_mac

all_core_src = $core_src $unix_core_src QtCore/io/qfilesystemengine_unix \
               $win_core_src $macos_core_src_mm

gen_hdr = QtCore/qtcoreexports QtCore/qconfig QtCore/qtdeprecationdefinitions

exe{qt6moc}: hxx{** -{$gen_hdr} +QtCore/Q*.} h{$gen_hdr}        \
             cxx{$core_src $moc_src}                            \
             testscript

exe{qt6moc}: cxx{$unix_core_src}:    include = $unix
exe{qt6moc}: mm{$macos_core_src_mm}: include = $macos
exe{qt6moc}: cxx{$win_core_src}:     include = $windows

# On Apple platforms qfilesystemengine_unix.cpp is compiled as Objective-C++
# (see upstream/qtbase/src/tools/bootstrap/CMakeLists.txt).
#
if $macos
  exe{qt6moc}: mm{QtCore/io/qfilesystemengine_unix.cpp}
else
  exe{qt6moc}: cxx{QtCore/io/qfilesystemengine_unix}: include = $unix

# Ensure included C and C++ source files and other files are included in the
# distribution.
#
exe{qt6moc}: cxx{keywords                               \
                 ppkeywords                             \
                 3rdparty/siphash/siphash}              \
             cxx{** -{$moc_src                          \
                      $core_src                         \
                      $unix_core_src                    \
                      QtCore/io/qfilesystemengine_unix  \
                      $win_core_src}}                   \
             file{cmake.conf}: include = adhoc

# Generated headers and source files.
#
using autoconf

QtCore/h{qconfig}: in.symbol = '$'

# Extract the copyright string from upstream/qtbase/.cmake.conf.
#
qt_copyright = $process.run_regex(cat $src_base/cmake.conf,             \
                                  '^\s*set\(QT_COPYRIGHT\s+"(.+)"\)',   \
                                  '\1')

# All-Qt public configuration header. Included by other Qt libraries via
# QtCore/qtconfiginclude.h.
#
# See the .in file for more information.
#
QtCore/h{qconfig}: QtCore/in{qconfig}
{
  autoconf.prefix = qconfig_

  QT_VERSION_STR="$version.major.$version.minor.$version.patch"
  QT_VERSION_MAJOR="$version.major"
  QT_VERSION_MINOR="$version.minor"
  QT_VERSION_PATCH="$version.patch"

  QT_COPYRIGHT="$qt_copyright"
}

QtCore/h{qtcoreexports}: QtCore/in{qtcoreexports}
{
  in.symbol = '@'
  header_base_name_upper = QTCOREEXPORTS
  module_define_infix    = CORE
}

# Deprecation cut-off macros. See libQt6Core/QtCore/buildfile for details.
#
QtCore/h{qtdeprecationdefinitions}: QtCore/in{qtdeprecationdefinitions}
{
  in.symbol = '@'
  QT_DISABLE_DEPRECATED_UP_TO = ($windows ? 0x040800 : 0x050000)
  QT_WARN_DEPRECATED_UP_TO    = 0x070000
}

exe{qt6moc}: $libs

# Header search directories.
#
# Add moc/ for include paths like <QtCore/qstring.h>.
#
# Add moc/QtCore/ for include paths like <qstring.h>.
#
# Add moc/QtCore/private/QtCore/private/ for include paths such as <qglobal_p.h>.
#
# Add moc/shared for a single include of <depfile_shared.h>.
#
cxx.poptions =+                                                                 \
  "-I$out_root/moc"        "-I$src_root/moc"                                    \
  "-I$out_root/moc/QtCore" "-I$src_root/moc/QtCore"                             \
                           "-I$src_root/moc/QtCore/private"                     \
                           "-I$src_root/moc/QtCore/private/QtCore"              \
                           "-I$src_root/moc/QtCore/private/QtCore/private"      \
                           "-I$src_root/moc/shared"

# Add platform-specific header directories.
#
# Every directory under mkspecs/ contains a unique `qplatformdefs.h`.
#
# Note that Mac OS with GCC is not supported by upstream (see README-DEV for
# details).
#
switch $cxx.target.class, $cxx.id, $cxx.target.system
{
  case 'linux', 'gcc'
    cxx.poptions += "-I$src_root/moc/mkspecs/linux-g++"
  case 'linux', 'clang'
    cxx.poptions += "-I$src_root/moc/mkspecs/linux-clang"
  case 'macos', 'clang-apple'
  {
    cxx.poptions += "-I$src_root/moc/mkspecs/macx-clang"
    cxx.libs     += -framework AppKit                   \
                    -framework CoreServices             \
                    -framework Foundation               \
                    -framework IOKit                    \
                    -framework Security                 \
                    -framework UniformTypeIdentifiers
  }
  case 'bsd', 'clang', 'freebsd'
    cxx.poptions += "-I$src_root/moc/mkspecs/freebsd-clang"
  case 'bsd', 'gcc', 'openbsd'
    cxx.poptions += "-I$src_root/moc/mkspecs/openbsd-g++"
  case 'bsd', 'gcc', 'netbsd'
    cxx.poptions += "-I$src_root/moc/mkspecs/netbsd-g++"
  case 'windows', 'msvc'
  {
    cxx.poptions += "-I$src_root/moc/mkspecs/win32-msvc"

    cxx.libs += ole32.lib advapi32.lib netapi32.lib shell32.lib user32.lib
  }
  case 'windows', 'msvc-clang' | 'clang'
  {
    cxx.poptions += "-I$src_root/moc/mkspecs/win32-clang-msvc"

    cxx.libs += ole32.lib advapi32.lib netapi32.lib shell32.lib user32.lib

    # Work around https://github.com/llvm/llvm-project/issues/25679 (see
    # upstream/qtbase/src/tools/bootstrap/CMakeLists.txt).
    #
    if ($cxx.id == 'msvc-clang')
      cxx.libs += \
        clang_rt.builtins-($cxx.target.cpu == 'aarch64' ? aarch64 : x86_64).lib
  }
  case 'windows', 'gcc', 'mingw32'
  {
    cxx.poptions += "-I$src_root/moc/mkspecs/win32-g++"
    cxx.coptions += -fno-keep-inline-dllexport
    cxx.libs     += -lole32 -ladvapi32 -lnetapi32 -lshell32 -luser32 -luuid
  }
}

# Required by QObjCWeakPointer (see
# upstream/qtbase/src/tools/bootstrap/CMakeLists.txt).
#
if $macos
  obj{QtCore/kernel/qcore_mac}: cxx.coptions += -fobjc-weak

cxx.poptions += -DQT_NO_CAST_FROM_ASCII

obj{$all_core_src}: cxx.poptions += $bootstrap_macros

# QT_NO_CAST_FROM_BYTEARRAY disables implicit conversions of QByteArray to
# char* and void*.
#
obj{$moc_src}: cxx.poptions += $compiler_macros                 \
                               -DQT_MOC                         \
                               -DQT_NO_CAST_FROM_BYTEARRAY      \
                               -DQT_NO_QPAIR                    \
                               -DQT_NO_URL_CAST_FROM_STRING     \
                               -DQT_USE_NODISCARD_FILE_OPEN


# Disable exceptions on all objects, including the QtCore ones, like upstream
# (which disables them for all targets that do not request them explicitly,
# including the bootstrap library; see qt_internal_set_exceptions_flags() in
# upstream/qtbase/cmake/QtFlagHandlingHelpers.cmake).
#
switch $cxx.class
{
  case 'gcc'
  {
    obj{$moc_src $all_core_src}:
    {
      cxx.poptions += -DQT_NO_EXCEPTIONS
      cxx.coptions += -fno-exceptions
    }
  }
  case 'msvc'
  {
    obj{$moc_src $all_core_src}:
    {
      cxx.poptions += -DQT_NO_EXCEPTIONS
      cxx.coptions += /EHs- /EHc-
    }
  }
}
