// These are the same contents generated by the upstream build if tracepoints
// are disabled (see qt_internal_create_tracepoints() in
// upstream/qtbase/cmake/QtTargetHelpers.cmake).
//
#include <private/qtrace_p.h>
